# Generated by Django 3.1.3 on 2020-11-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='HybridXR', max_length=50)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('contact_title', models.CharField(max_length=100, null=True)),
                ('contact_address', models.CharField(max_length=100, null=True)),
                ('contact_email', models.EmailField(max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='media/')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('isRelated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
