# Generated by Django 3.1.3 on 2020-11-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_companydata_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='company_name',
            field=models.CharField(default='HybridXR', max_length=50),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='contact_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='contact_email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='contact_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='footer_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
