# Generated by Django 3.0.7 on 2020-11-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201104_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isRelated',
            field=models.BooleanField(default=False),
        ),
    ]
