# Generated by Django 3.1.3 on 2020-11-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_companydata_contact_address_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='footer_title',
        ),
        migrations.AlterField(
            model_name='companydata',
            name='contact_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='contact_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
